[package]
name = "valensas-actuator"
version = "0.1.3"
edition = "2021"
description = "A library that provides Prometheus metrics collection capabilities for Rocket applications."
license = "MIT"
repository = "https://github.com/Valensas/rust-actuator"

[dependencies]
prometheus = "0.13.3"

[dependencies.rocket]
version = "=0.5.0-rc.3"
features = ["json"]