[package]
name = "valensas-actuator"
version = "0.1.2"
edition = "2021"
description = "A library that provides Prometheus metrics collection capabilities for Rocket applications."
license = "MIT"

[dependencies]
prometheus = "0.13.3"

[dependencies.rocket]
version = "=0.5.0-rc.3"
features = ["json"]